# Generated by Django 2.2.5 on 2019-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de la conferencia')),
                ('fecha', models.DateTimeField(verbose_name='fecha y hora')),
                ('lugar', models.CharField(max_length=200)),
                ('conferencista', models.CharField(max_length=200, verbose_name='nombre del conferencista')),
                ('asistentes', models.ManyToManyField(to='listas.Persona')),
            ],
        ),
    ]
